[package]
name = "oj-back"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
salvo = "0.64.0"
serde = "1.0.204"
tokio = { version = "1", features = ["macros"] }
toml = "0.8.19"
tracing = "0.1"
tracing-subscriber = "0.3"
