[server]
host = "127.0.0.1"
port = 8001

[mysql]
host = "127.0.0.1"
port = 3306
username = "root"
password = "19260817"
database = "oj"

[judger]
url = "http://127.0.0.1:8100"

[auth]
secret = "jzm19260817"
expires = 14
